/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.mvc.view;

import edu.ijse.mvc.controller.CustController;
import edu.ijse.mvc.dto.CustDto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class CustView extends javax.swing.JFrame {
    private CustController custController;
    /**
     * Creates new form CustView
     */
    public CustView() throws Exception{
        initComponents();
        custController = new CustController();
        loadtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbCustID = new javax.swing.JLabel();
        txtCustID = new javax.swing.JTextField();
        txtCustTitle = new javax.swing.JTextField();
        lbCustTitle = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        lbCustName = new javax.swing.JLabel();
        txtCustDOB = new javax.swing.JTextField();
        lbCustDOB = new javax.swing.JLabel();
        txtCustSalary = new javax.swing.JTextField();
        lbCustSalary = new javax.swing.JLabel();
        txtCustCity = new javax.swing.JTextField();
        lbCustCity = new javax.swing.JLabel();
        txtCustZip = new javax.swing.JTextField();
        lbCustZip = new javax.swing.JLabel();
        txtCustAddress = new javax.swing.JTextField();
        lbCustAddress = new javax.swing.JLabel();
        txtCustProvince = new javax.swing.JTextField();
        lbCustProvince = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCust = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Customer form");

        lbCustID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustID.setText("Customer ID");

        txtCustID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIDActionPerformed(evt);
            }
        });

        txtCustTitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustTitleActionPerformed(evt);
            }
        });

        lbCustTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustTitle.setText("Title");

        txtCustName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });

        lbCustName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustName.setText("Name");

        txtCustDOB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustDOBActionPerformed(evt);
            }
        });

        lbCustDOB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustDOB.setText("Date of Birth");

        txtCustSalary.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustSalaryActionPerformed(evt);
            }
        });

        lbCustSalary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustSalary.setText("Salary");

        txtCustCity.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustCityActionPerformed(evt);
            }
        });

        lbCustCity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustCity.setText("City");

        txtCustZip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustZipActionPerformed(evt);
            }
        });

        lbCustZip.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustZip.setText("Postal Code");

        txtCustAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustAddressActionPerformed(evt);
            }
        });

        lbCustAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustAddress.setText("Address");

        txtCustProvince.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCustProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustProvinceActionPerformed(evt);
            }
        });

        lbCustProvince.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbCustProvince.setText("Province");

        btnSave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblCust.setBackground(new java.awt.Color(240, 240, 240));
        tblCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCust.setGridColor(new java.awt.Color(153, 153, 153));
        tblCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCust);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCustTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addComponent(lbCustCity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCustCity, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCustTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbCustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCustSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbCustProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCustSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustID, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCustTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCustAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCustName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustCity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCustCity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCustDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCustProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCustSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustIDActionPerformed

    private void txtCustTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustTitleActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtCustDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustDOBActionPerformed

    private void txtCustSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustSalaryActionPerformed

    private void txtCustCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustCityActionPerformed

    private void txtCustZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustZipActionPerformed

    private void txtCustAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustAddressActionPerformed

    private void txtCustProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustProvinceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteCust();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveCust();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustMouseClicked
        try {
            searchCust();
        } catch (SQLException ex) {
            Logger.getLogger(CustView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblCustMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateCust();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CustView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CustView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CustView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CustView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CustView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCustAddress;
    private javax.swing.JLabel lbCustCity;
    private javax.swing.JLabel lbCustDOB;
    private javax.swing.JLabel lbCustID;
    private javax.swing.JLabel lbCustName;
    private javax.swing.JLabel lbCustProvince;
    private javax.swing.JLabel lbCustSalary;
    private javax.swing.JLabel lbCustTitle;
    private javax.swing.JLabel lbCustZip;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tblCust;
    private javax.swing.JTextField txtCustAddress;
    private javax.swing.JTextField txtCustCity;
    private javax.swing.JTextField txtCustDOB;
    private javax.swing.JTextField txtCustID;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustProvince;
    private javax.swing.JTextField txtCustSalary;
    private javax.swing.JTextField txtCustTitle;
    private javax.swing.JTextField txtCustZip;
    // End of variables declaration//GEN-END:variables

    private void saveCust() {
        try {
            CustDto dto = new CustDto(txtCustID.getText(), txtCustTitle.getText(), txtCustName.getText(), txtCustDOB.getText(), Double.parseDouble(txtCustSalary.getText()), txtCustAddress.getText(), txtCustCity.getText(), txtCustProvince.getText(), txtCustZip.getText());
            String resp;
            resp = custController.saveCust(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearform();
            loadtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error to save");
        }    
    }
    
    private void clearform() {
        txtCustID.setText("");
        txtCustTitle.setText("");
        txtCustName.setText("");
        txtCustDOB.setText("");
        txtCustSalary.setText("");
        txtCustAddress.setText("");
        txtCustCity.setText("");
        txtCustProvince.setText("");
        txtCustZip.setText("");
    }

    private void loadtable() {
        try {
            String columns[] = {"Customer ID","Title","Name","Date of Birth","Salary","Address","City","Province","Postal Code"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
        
            tblCust.setModel(dtm);
            ArrayList<CustDto> custDtos = custController.getAllCust();
            for(CustDto dto:custDtos){
                Object[] rowData = {dto.getCustID(),dto.getCustTitle(),dto.getCustName(),dto.getDob(),dto.getSalary(),dto.getCustAddress(),dto.getCustCity(),dto.getCustProvince(),dto.getZip()};
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at load table");
        }
    }

    private void searchCust() throws SQLException {
        try {
            String custId = tblCust.getValueAt(tblCust.getSelectedRow(), 0).toString();
            CustDto dto = custController.searchCust(custId);
        
        if (dto != null) {
            txtCustID.setText(dto.getCustID());
            txtCustTitle.setText(dto.getCustTitle());
            txtCustName.setText(dto.getCustName());
            txtCustDOB.setText(dto.getDob());
            txtCustSalary.setText(Double.toString(dto.getSalary()));
            txtCustAddress.setText(dto.getCustAddress());
            txtCustCity.setText(dto.getCustCity());
            txtCustProvince.setText(dto.getCustProvince());
            txtCustZip.setText(dto.getZip());
        } else {
            JOptionPane.showMessageDialog(this, "Error at search customer");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at search customer");
        }
    } 

    private void deleteCust() {
        try {
            String custId = txtCustID.getText();
            String resp = custController.deleteCust(custId);
            JOptionPane.showMessageDialog(this, resp);
            clearform();
            loadtable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error at delete cust");
        }
    }

    private void updateCust() {
        try {
            CustDto dto = new CustDto(txtCustID.getText(), txtCustTitle.getText(), txtCustName.getText(), txtCustDOB.getText(), Double.parseDouble(txtCustSalary.getText()), txtCustAddress.getText(), txtCustCity.getText(), txtCustProvince.getText(), txtCustZip.getText());
            String resp = custController.updateCust(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearform();
            loadtable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at update customer");
        }
    }
}
